import 'dart:core';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import '../models/ImagesDisplayModel.dart';

class NativeView extends StatelessWidget {
  NativeView({super.key});

  final List<Widget> design = [
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/1.jpg",
      id: 'ID: 1',
      status: "available",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/2.jpg",
      id: 'ID: 2',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/3.jpg",
      id: 'ID: 3',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/4.jpg",
      id: 'ID: 4',
      status: "available",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/5.jpg",
      id: 'ID: 5',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/6.jpg",
      id: 'ID: 6',
      status: "available",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/7.jpg",
      id: 'ID: 7',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/8.jpg",
      id: 'ID: 8',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/9.jpg",
      id: 'ID: 9',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/10.jpg",
      id: 'ID: 10',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/11.jpg",
      id: 'ID: 11',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/12.jpg",
      id: 'ID: 12',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/13.jpg",
      id: 'ID: 13',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/14.jpg",
      id: 'ID: 14',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/15.jpg",
      id: 'ID: 15',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/16.jpg",
      id: 'ID: 16',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/17.jpg",
      id: 'ID: 17',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/18.jpg",
      id: 'ID: 18',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/19.jpg",
      id: 'ID: 19',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/20.jpg",
      id: 'ID: 20',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/21.jpg",
      id: 'ID: 21',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/22.jpg",
      id: 'ID: 22',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/23.jpg",
      id: 'ID: 23',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/24.jpg",
      id: 'ID: 24',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/25.jpg",
      id: 'ID: 25',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/26.jpg",
      id: 'ID: 26',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/27.jpg",
      id: 'ID: 27',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/28.jpg",
      id: 'ID: 28',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/29.jpg",
      id: 'ID: 29',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/30.jpg",
      id: 'ID: 30',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/31.jpg",
      id: 'ID: 31',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/32.jpg",
      id: 'ID: 32',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/33.jpg",
      id: 'ID: 33',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/34.jpg",
      id: 'ID: 34',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/35.jpg",
      id: 'ID: 35',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/36.jpg",
      id: 'ID: 36',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/37.jpg",
      id: 'ID: 37',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/38.jpg",
      id: 'ID: 38',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/39.jpg",
      id: 'ID: 39',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/40.jpg",
      id: 'ID: 40',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/41.jpg",
      id: 'ID: 41',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/42.jpg",
      id: 'ID: 42',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/43.jpg",
      id: 'ID: 43',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/44.jpg",
      id: 'ID: 44',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/45.jpg",
      id: 'ID: 45',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/46.jpg",
      id: 'ID: 46',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/47.jpg",
      id: 'ID: 47',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/48.jpg",
      id: 'ID: 48',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/49.jpg",
      id: 'ID: 49',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/50.jpg",
      id: 'ID: 50',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/51.jpg",
      id: 'ID: 51',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/52.jpg",
      id: 'ID: 52',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/53.jpg",
      id: 'ID: 53',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/54.jpg",
      id: 'ID: 54',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/55.jpg",
      id: 'ID: 55',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/56.jpg",
      id: 'ID: 56',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/57.jpg",
      id: 'ID: 57',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/58.jpg",
      id: 'ID: 58',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/59.jpg",
      id: 'ID: 59',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/60.jpg",
      id: 'ID: 60',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/61.jpg",
      id: 'ID: 61',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/62.jpg",
      id: 'ID: 62',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/63.jpg",
      id: 'ID: 63',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/64.jpg",
      id: 'ID: 64',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/65.jpg",
      id: 'ID: 65',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/66.jpg",
      id: 'ID: 66',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/67.jpg",
      id: 'ID: 67',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/68.jpg",
      id: 'ID: 68',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/69.jpg",
      id: 'ID: 69',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/70.jpg",
      id: 'ID: 70',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/71.jpg",
      id: 'ID: 71',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/72.jpg",
      id: 'ID: 72',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/73.jpg",
      id: 'ID: 73',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/74.jpg",
      id: 'ID: 74',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/75.jpg",
      id: 'ID: 75',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/76.jpg",
      id: 'ID: 76',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/77.jpg",
      id: 'ID: 77',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/78.jpg",
      id: 'ID: 78',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/79.jpg",
      id: 'ID: 79',
      status: "On-demand",
    ),
    const ImagesDisplayModel(
      text: "Men native wear",
      img: "assets/images/80.jpg",
      id: 'ID: 80',
      status: "On-demand",
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
